//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chatdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int ChatId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> BuyOrSellId { get; set; }
        public string chat1 { get; set; }
    }
}
